# Generated by Django 3.0.5 on 2020-10-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreg', '0002_auto_20201029_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='input1',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='input2',
        ),
        migrations.AddField(
            model_name='reg',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=120),
        ),
        migrations.AddField(
            model_name='reg',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=120),
        ),
        migrations.AddField(
            model_name='reg',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=120),
        ),
    ]
