# Generated by Django 3.0.5 on 2020-10-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreg', '0004_regex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regex',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='email',
            new_name='expression',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='password',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='username',
        ),
    ]
